version: 2
updates:
  - package-ecosystem: "swift"
    directory: "/Tuist"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Asia/Seoul"
    labels: ["dependencies", "tuist", "swiftpm"]
    rebase-strategy: "auto"
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:10"
      timezone: "Asia/Seoul"
    labels: ["dependencies", "github-actions"]
    rebase-strategy: "auto"
    open-pull-requests-limit: 5