cache_path: .swiftlint_cache

reporter: xcode

included:
  - Projects/**/Sources/**

excluded:
  - Tuist/**
  - .build
  - build
  - Derived
  - DerivedData
  - "**/*.xcodeproj/**"
  - "**/*.xcworkspace/**"
  - "**/Generated/**"
  - "**/*.generated.swift"
  - "**/Demo/**"
  - "**/*Tests/**"

disabled_rules:
  - todo

analyzer_rules:
  - explicit_self

opt_in_rules:
  - anyobject_protocol
  - attributes
  - closure_spacing
  - collection_alignment
  - contains_over_first_not_nil
  - empty_count
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - modifier_order
  - multiline_arguments
  - multiline_parameters
  - operator_usage_whitespace
  - ordered_imports
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition
  - force_cast
  - force_try
  - force_unwrapping

line_length:
  warning: 120
  error: 140
  ignores_urls: true
  ignores_comments: true
  ignores_interpolated_strings: true

file_length:
  warning: 500
  error: 800

type_body_length:
  warning: 300
  error: 400

function_body_length:
  warning: 50
  error: 80

identifier_name:
  min_length: 2
  max_length: 50
  excluded: [id, i, x, y, vm, to, on, in, URL, ID, API]

type_name:
  max_length: 50
  allowed_symbols: ["_"]

force_cast: warning
force_try: warning
force_unwrapping: warning

custom_rules:
  no_print_in_app:
    name: "print() 대신 Logger 사용"
    regex: "\\bprint\\("
    message: "디버깅 시 print() 대신 OSLog 또는 Logger를 사용해주세요."
    severity: warning