# true로 설정하면 사용자가 템플릿을 사용하지 않고 빈 이슈를 생성할 수 있습니다.
# false로 설정하여 반드시 템플릿 중 하나를 선택하도록 강제합니다.
blank_issues_enabled: false

# 이슈 트래커 외에 다른 채널로 사용자를 안내하는 링크를 추가합니다.
contact_links:
  - name: "🤔 질문 및 토론 (Questions & Discussion)"
    # 👇 이 URL을 실제 WePLi 프로젝트의 GitHub Discussions URL로 변경해주세요.
    url: https://github.com/unib35/WePLi-iOS/discussions
    about: "프로젝트에 대한 간단한 질문이나 새로운 아이디어 제안, 자유로운 토론은 여기서 해주세요."