default_platform(:ios)

platform :ios do
  desc "Run unit tests on a simulator"
  lane :test do
    run_tests(
      workspace: "WePLi.xcworkspace",
      scheme: "WePLi",
      clean: true,
      code_coverage: true
    )
  end

  desc "Archive (no upload) just to verify signing/payload"
  lane :archive do
    build_app(
      workspace: "WePLi.xcworkspace",
      scheme: "WePLi",
      export_method: "development",
      clean: true
    )
  end
end